#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.miniconda/bin:$PATH
export PATH=$HOME/Development/flutter/flutter/bin:$PATH
export PATH=/usr/local/pgsql/bin:$PATH
export PATH=/usr/pgsql-10/bin:$PATH
export SUDO_ASKPASS=beesu:$PATH
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
